### ISSUE TITLE
submission notebook is not working

### ISSUE THREAD

**Issue by mireklzicar** [Oloren-AI/OCE-TDC#1]
Hi! I am trying to run the submission notebook, but it is not working. There is no "model_from_dict" function defined. Also when I try it via for instance oce.create_BC(models['BaseBoosting xXOn1QFI']) I am having some auth error from retrieval of http://metadata.google.internal/computeMetadata.

**Comment by davidzqhuang** [comment]
Looking into this for you, you are right that it should be oce.create_BC not model_from_dict.

Could you post the full traceback, so we can figure out what's going on?

We do host model checkpoint files, etc. on google cloud but those should be public, so I'm not quite sure what that would be.

**Comment by mireklzicar** [comment]
`Downloading OlorenVec checkpoint...
ERROR:gcsfs:_request out of retries on exception: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Engine metadata service. Status: 404 Response:\nb''", <google.auth.transport.requests._Response object at 0x7f7754a8d880>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/google/auth/compute_engine/credentials.py", line 111, in refresh
    self._retrieve_info(request)
  File "/usr/local/lib/python3.8/dist-packages/google/auth/compute_engine/credentials.py", line 87, in _retrieve_info
    info = _metadata.get_service_account_info(
  File "/usr/local/lib/python3.8/dist-packages/google/auth/compute_engine/_metadata.py", line 234, in get_service_account_info
    return get(request, path, params={"recursive": "true"})
  File "/usr/local/lib/python3.8/dist-packages/google/auth/compute_engine/_metadata.py", line 182, in get
    raise exceptions.TransportError(
google.auth.exceptions.TransportError: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Engine metadata service. Status: 404 Response:\nb''", <google.auth.transport.requests._Response object at 0x7f7754a8d880>)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gcsfs/retry.py", line 115, in retry_request
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/gcsfs/core.py", line 405, in _request
    headers=self._get_headers(headers),
  File "/usr/local/lib/python3.8/dist-packages/gcsfs/core.py", line 384, in _get_headers
    self.credentials.apply(out)
  File "/usr/local/lib/python3.8/dist-packages/gcsfs/credentials.py", line 185, in apply
    self.maybe_refresh()
  File "/usr/local/lib/python3.8/dist-packages/gcsfs/credentials.py", line 180, in maybe_refresh
    self.credentials.refresh(req)
  File "/usr/local/lib/python3.8/dist-packages/google/auth/compute_engine/credentials.py", line 117, in refresh
    six.raise_from(new_exc, caught_exc)
  File "<string>", line 3, in raise_from
google.auth.exceptions.RefreshError: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Engine metadata service. Status: 404 Response:\nb''", <google.auth.transport.requests._Response object at 0x7f7754a8d880>)
---------------------------------------------------------------------------
TransportError                            Traceback (most recent call last)
[/usr/local/lib/python3.8/dist-packages/google/auth/compute_engine/credentials.py](https://localhost:8080/#) in refresh(self, request)
    110         try:
--> 111             self._retrieve_info(request)
    112             self.token, self.expiry = _metadata.get_service_account_token(

28 frames
[/usr/local/lib/python3.8/dist-packages/google/auth/compute_engine/credentials.py](https://localhost:8080/#) in _retrieve_info(self, request)
     86         """
---> 87         info = _metadata.get_service_account_info(
     88             request, service_account=self._service_account_email

[/usr/local/lib/python3.8/dist-packages/google/auth/compute_engine/_metadata.py](https://localhost:8080/#) in get_service_account_info(request, service_account)
    233     # for more on the use of 'recursive'.
--> 234     return get(request, path, params={"recursive": "true"})
    235 

[/usr/local/lib/python3.8/dist-packages/google/auth/compute_engine/_metadata.py](https://localhost:8080/#) in get(request, path, root, params, recursive, retry_count)
    181     else:
--> 182         raise exceptions.TransportError(
    183             "Failed to retrieve {} from the Google Compute Engine "

TransportError: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Engine metadata service. Status: 404 Response:\nb''", <google.auth.transport.requests._Response object at 0x7f7754a8d880>)

The above exception was the direct cause of the following exception:

RefreshError                              Traceback (most recent call last)
[<ipython-input-20-82e0e44d0357>](https://localhost:8080/#) in <module>
----> 1 oce.create_BC(models['BaseBoosting xXOn1QFI'])

[/usr/local/lib/python3.8/dist-packages/olorenchemengine/internal.py](https://localhost:8080/#) in create_BC(d)
    841             else:
    842                 if isinstance(arg, list):
--> 843                     arg = [
    844                         create_BC(x)
    845                         if isinstance(x, dict)

[/usr/local/lib/python3.8/dist-packages/olorenchemengine/internal.py](https://localhost:8080/#) in <listcomp>(.0)
    842                 if isinstance(arg, list):
    843                     arg = [
--> 844                         create_BC(x)
    845                         if isinstance(x, dict)
    846                         and ("BC_class_name" in x.keys() or "REMOTE_ID" in x.keys())

[/usr/local/lib/python3.8/dist-packages/olorenchemengine/internal.py](https://localhost:8080/#) in create_BC(d)
    838                 "BC_class_name" in arg.keys() or "REMOTE_ID" in arg.keys()
    839             ):
--> 840                 args.append(create_BC(arg))
    841             else:
    842                 if isinstance(arg, list):

[/usr/local/lib/python3.8/dist-packages/olorenchemengine/internal.py](https://localhost:8080/#) in create_BC(d)
    868                 kwargs[k] = v
    869 
--> 870     return BaseClass.Registry()[d["BC_class_name"]](*args, **kwargs)
    871 
    872 

[/usr/local/lib/python3.8/dist-packages/olorenchemengine/internal.py](https://localhost:8080/#) in wrapper(self, *args, **kwargs)
    239             self.kwargs = {k: v for k, v in kwargs.items() if k not in ignored_kwargs}
    240         if _runtime.is_local:
--> 241             return func(self, *args, **kwargs)
    242         import uuid
    243 

[/usr/local/lib/python3.8/dist-packages/olorenchemengine/representations.py](https://localhost:8080/#) in __init__(self, model_path, num_tasks, log, **kwargs)
   1340 
   1341                 fs = gcsfs.GCSFileSystem()
-> 1342                 with fs.open("gs://oloren-public-data/saves/olorenvec.ckpt", "rb") as f:
   1343                     with open(path, "wb") as out:
   1344                         out.write(f.read())

[/usr/local/lib/python3.8/dist-packages/fsspec/spec.py](https://localhost:8080/#) in open(self, path, mode, block_size, cache_options, compression, **kwargs)
   1104         else:
   1105             ac = kwargs.pop("autocommit", not self._intrans)
-> 1106             f = self._open(
   1107                 path,
   1108                 mode=mode,

[/usr/local/lib/python3.8/dist-packages/gcsfs/core.py](https://localhost:8080/#) in _open(self, path, mode, block_size, cache_options, acl, consistency, metadata, autocommit, fixed_key_metadata, generation, **kwargs)
   1289             block_size = self.default_block_size
   1290         const = consistency or self.consistency
-> 1291         return GCSFile(
   1292             self,
   1293             path,

[/usr/local/lib/python3.8/dist-packages/gcsfs/core.py](https://localhost:8080/#) in __init__(self, gcsfs, path, mode, block_size, autocommit, cache_type, cache_options, acl, consistency, metadata, content_type, timeout, fixed_key_metadata, generation, **kwargs)
   1446             raise OSError("Attempt to open a bucket")
   1447         self.generation = _coalesce_generation(generation, path_generation)
-> 1448         super().__init__(
   1449             gcsfs,
   1450             path,

[/usr/local/lib/python3.8/dist-packages/fsspec/spec.py](https://localhost:8080/#) in __init__(self, fs, path, mode, block_size, autocommit, cache_type, cache_options, size, **kwargs)
   1460                 self.size = size
   1461             else:
-> 1462                 self.size = self.details["size"]
   1463             self.cache = caches[cache_type](
   1464                 self.blocksize, self._fetch_range, self.size, **cache_options

[/usr/local/lib/python3.8/dist-packages/gcsfs/core.py](https://localhost:8080/#) in details(self)
   1482     def details(self):
   1483         if self._details is None:
-> 1484             self._details = self.fs.info(self.path, generation=self.generation)
   1485         return self._details
   1486 

[/usr/local/lib/python3.8/dist-packages/fsspec/asyn.py](https://localhost:8080/#) in wrapper(*args, **kwargs)
    111     def wrapper(*args, **kwargs):
    112         self = obj or args[0]
--> 113         return sync(self.loop, func, *args, **kwargs)
    114 
    115     return wrapper

[/usr/local/lib/python3.8/dist-packages/fsspec/asyn.py](https://localhost:8080/#) in sync(loop, func, timeout, *args, **kwargs)
     96         raise FSTimeoutError from return_result
     97     elif isinstance(return_result, BaseException):
---> 98         raise return_result
     99     else:
    100         return return_result

[/usr/local/lib/python3.8/dist-packages/fsspec/asyn.py](https://localhost:8080/#) in _runner(event, coro, result, timeout)
     51         coro = asyncio.wait_for(coro, timeout=timeout)
     52     try:
---> 53         result[0] = await coro
     54     except Exception as ex:
     55         result[0] = ex

[/usr/local/lib/python3.8/dist-packages/gcsfs/core.py](https://localhost:8080/#) in _info(self, path, generation, **kwargs)
    780         # Check exact file path
    781         try:
--> 782             exact = await self._get_object(path)
    783             # this condition finds a "placeholder" - still need to check if it's a directory
    784             if exact["size"] or not exact["name"].endswith("/"):

[/usr/local/lib/python3.8/dist-packages/gcsfs/core.py](https://localhost:8080/#) in _get_object(self, path)
    493         # fall back to a bucket list + filter to object name (storage.objects.list).
    494         try:
--> 495             res = await self._call(
    496                 "GET", "b/{}/o/{}", bucket, key, json_out=True, generation=generation
    497             )

[/usr/local/lib/python3.8/dist-packages/gcsfs/core.py](https://localhost:8080/#) in _call(self, method, path, json_out, info_out, *args, **kwargs)
    420     ):
    421         logger.debug(f"{method.upper()}: {path}, {args}, {kwargs.get('headers')}")
--> 422         status, headers, info, contents = await self._request(
    423             method, path, *args, **kwargs
    424         )

<decorator-gen-119> in _request(self, method, path, headers, json, data, *args, **kwargs)

[/usr/local/lib/python3.8/dist-packages/gcsfs/retry.py](https://localhost:8080/#) in retry_request(func, retries, *args, **kwargs)
    145                     "%s out of retries on exception: %s" % (func.__name__, e)
    146                 )
--> 147                 raise e
    148             if is_retriable(e):
    149                 logger.debug("%s retrying after exception: %s" % (func.__name__, e))

[/usr/local/lib/python3.8/dist-packages/gcsfs/retry.py](https://localhost:8080/#) in retry_request(func, retries, *args, **kwargs)
    113             if retry > 0:
    114                 await asyncio.sleep(min(random.random() + 2 ** (retry - 1), 32))
--> 115             return await func(*args, **kwargs)
    116         except (
    117             HttpError,

[/usr/local/lib/python3.8/dist-packages/gcsfs/core.py](https://localhost:8080/#) in _request(self, method, path, headers, json, data, *args, **kwargs)
    403             params=self._get_params(kwargs),
    404             json=json,
--> 405             headers=self._get_headers(headers),
    406             data=data,
    407             timeout=self.requests_timeout,

[/usr/local/lib/python3.8/dist-packages/gcsfs/core.py](https://localhost:8080/#) in _get_headers(self, headers)
    382         if "User-Agent" not in out:
    383             out["User-Agent"] = "python-gcsfs/" + version
--> 384         self.credentials.apply(out)
    385         return out
    386 

[/usr/local/lib/python3.8/dist-packages/gcsfs/credentials.py](https://localhost:8080/#) in apply(self, out)
    183     def apply(self, out):
    184         """Insert credential headers in-place to a dictionary"""
--> 185         self.maybe_refresh()
    186         if self.credentials is not None:
    187             self.credentials.apply(out)

[/usr/local/lib/python3.8/dist-packages/gcsfs/credentials.py](https://localhost:8080/#) in maybe_refresh(self)
    178                     return  # repeat to avoid race (but don't want lock in common case)
    179                 logger.debug("GCS refresh")
--> 180                 self.credentials.refresh(req)
    181                 self.apply(self.heads)
    182 

[/usr/local/lib/python3.8/dist-packages/google/auth/compute_engine/credentials.py](https://localhost:8080/#) in refresh(self, request)
    115         except exceptions.TransportError as caught_exc:
    116             new_exc = exceptions.RefreshError(caught_exc)
--> 117             six.raise_from(new_exc, caught_exc)
    118 
    119     @property

/usr/local/lib/python3.8/dist-packages/six.py in raise_from(value, from_value)

RefreshError: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Engine metadata service. Status: 404 Response:\nb''", <google.auth.transport.requests._Response object at 0x7f7754a8d880>)`

**Comment by davidzqhuang** [comment]
Ok, looking into the service account issue, in the meantime all files go in ~/.oce, and can be found at https://console.cloud.google.com/storage/browser/oloren-public-data;tab=objects?forceOnBucketsSortingFiltering=false&project=oloren-ai&prefix=&forceOnObjectsSortingFiltering=false. You have to have a google account but any google account works. 

In this case the file olorenvec.ckpt, https://storage.googleapis.com/oloren-public-data/saves/olorenvec.ckpt, goes in ~/.oce/olorencheckpoint.ckpt

Will look for a more general solution.

**Comment by mireklzicar** [comment]
Well, another error is now, if I am trying to create the model it says it has problem with pytorch_lightning. But that is weird because I have pytorch_lightning installed.

**Comment by mireklzicar** [comment]
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-3-82e0e44d0357>](https://localhost:8080/#) in <module>
----> 1 oce.create_BC(models['BaseBoosting xXOn1QFI'])

8 frames
[/usr/local/lib/python3.8/dist-packages/olorenchemengine/internal.py](https://localhost:8080/#) in create_BC(d)
    841             else:
    842                 if isinstance(arg, list):
--> 843                     arg = [
    844                         create_BC(x)
    845                         if isinstance(x, dict)

[/usr/local/lib/python3.8/dist-packages/olorenchemengine/internal.py](https://localhost:8080/#) in <listcomp>(.0)
    842                 if isinstance(arg, list):
    843                     arg = [
--> 844                         create_BC(x)
    845                         if isinstance(x, dict)
    846                         and ("BC_class_name" in x.keys() or "REMOTE_ID" in x.keys())

[/usr/local/lib/python3.8/dist-packages/olorenchemengine/internal.py](https://localhost:8080/#) in create_BC(d)
    838                 "BC_class_name" in arg.keys() or "REMOTE_ID" in arg.keys()
    839             ):
--> 840                 args.append(create_BC(arg))
    841             else:
    842                 if isinstance(arg, list):

[/usr/local/lib/python3.8/dist-packages/olorenchemengine/internal.py](https://localhost:8080/#) in create_BC(d)
    868                 kwargs[k] = v
    869 
--> 870     return BaseClass.Registry()[d["BC_class_name"]](*args, **kwargs)
    871 
    872 

[/usr/local/lib/python3.8/dist-packages/olorenchemengine/internal.py](https://localhost:8080/#) in wrapper(self, *args, **kwargs)
    239             self.kwargs = {k: v for k, v in kwargs.items() if k not in ignored_kwargs}
    240         if _runtime.is_local:
--> 241             return func(self, *args, **kwargs)
    242         import uuid
    243 

[/usr/local/lib/python3.8/dist-packages/olorenchemengine/representations.py](https://localhost:8080/#) in __init__(self, model_path, num_tasks, log, **kwargs)
   1349             [
   1350                 (k.replace("model.", ""), v)
-> 1351                 for k, v in torch.load(path, map_location=oce.CONFIG["DEVICE"])[
   1352                     "state_dict"
   1353                 ].items()

[/usr/local/lib/python3.8/dist-packages/torch/serialization.py](https://localhost:8080/#) in load(f, map_location, pickle_module, weights_only, **pickle_load_args)
    787                     except RuntimeError as e:
    788                         raise pickle.UnpicklingError(UNSAFE_MESSAGE + str(e)) from None
--> 789                 return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
    790         if weights_only:
    791             try:

[/usr/local/lib/python3.8/dist-packages/torch/serialization.py](https://localhost:8080/#) in _load(zip_file, map_location, pickle_module, pickle_file, **pickle_load_args)
   1129     unpickler = UnpicklerWrapper(data_file, **pickle_load_args)
   1130     unpickler.persistent_load = persistent_load
-> 1131     result = unpickler.load()
   1132 
   1133     torch._utils._validate_loaded_sparse_tensors()

[/usr/local/lib/python3.8/dist-packages/torch/serialization.py](https://localhost:8080/#) in find_class(self, mod_name, name)
   1122                     pass
   1123             mod_name = load_module_mapping.get(mod_name, mod_name)
-> 1124             return super().find_class(mod_name, name)
   1125 
   1126     # Load the data (which may in turn use `persistent_load` to load tensors)

ModuleNotFoundError: No module named 'pytorch_lightning.callbacks'; 'pytorch_lightning' is not a package

**Comment by mireklzicar** [comment]
Maybe can you please upload a version of the submission notebook that is working on your side?

**Comment by davidzqhuang** [comment]
The currently uploaded submission notebook is working on our side and was run through prior to the submission the unfortunate "model_from_dict" was a formatting issue that cropped up while we were cleaning up the notebook. The notebook takes a while to run to competition but I've left rerunning it for a bit now and I've got no errors.

Moreover, given the the nature of the errors you are facing, it seems like an installation issue specific to your machine. This could crop up if you have some sort of specially defined paths or environment structure, or if you are executing notebooks in a kernel different than your normal python environment. It is difficult to debug that from our end with limited information; we aren't sure which of these situations apply.

**Comment by mireklzicar** [comment]
Now it is working also on my side, and it really has the reported results. Incredible! Turns out the previous error were some depenciencies on google colab; solved by reruning oce.MISSING_DEPENDENCIES(). Thanks.

**Comment by davidzqhuang** [comment]
I'm glad it works for you, that's what we are going for :)! Please get in touch if you have any other questions
